// Single source of truth for the audit-action → lucide-icon mapping.
//
// Three surfaces render audit entries with the same iconography and MUST stay
// in sync: the home `RecentActivityCard`, the `/audit` log rows, and the
// employee-profile history tab. Before this module the map lived inline in all
// three; step 22 extracted it here so adding an `AuditAction` only touches one
// place. The `Record<AuditAction, LucideIcon>` typing makes the map exhaustive
// at compile time — a new action without an icon is a build error.

import {
  Archive,
  ArrowRightLeft,
  BadgeCheck,
  CheckCircle,
  CirclePlay,
  ClipboardCheck,
  Drama,
  Eye,
  FileCheck,
  FileCheck2,
  FilePenLine,
  FilePlus,
  FileX,
  Forward,
  HelpCircle,
  KeyRound,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailPlus,
  MessageCircle,
  Pencil,
  PenLine,
  Plus,
  RefreshCw,
  Send,
  SendHorizontal,
  ShieldCheck,
  ShieldOff,
  ShieldX,
  Trash2,
  Upload,
  UserCheck,
  UserCog,
  UserPlus,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

import type { AuditAction } from '@/types/domain';

export const ACTION_ICON: Record<AuditAction, LucideIcon> = {
  CREATE: Plus,
  UPDATE: Pencil,
  DELETE: Trash2,
  ARCHIVE: Archive,
  LOGIN: LogIn,
  LOGOUT: LogOut,
  PASSWORD_CHANGED: KeyRound,
  UNIT_TRANSFER: ArrowRightLeft,
  CERTIFICATE_UPLOADED: Upload,
  CERTIFICATE_APPROVED: ShieldCheck,
  CERTIFICATE_REJECTED: ShieldOff,
  CERTIFICATE_REVOKED: ShieldX,
  PROFILE_CHANGE_REQUESTED: UserCog,
  PROFILE_CHANGE_APPROVED: UserCheck,
  POV_SWITCHED: Drama,
  DOCUMENT_CREATED: FilePlus,
  DOCUMENT_SENT_FOR_REVIEW: Send,
  DOCUMENT_APPROVED: FileCheck,
  DOCUMENT_REJECTED: FileX,
  DOCUMENT_SIGNED: FilePenLine,
  DOCUMENT_CLOSED: FileCheck2,
  DOCUMENT_VIEWED: Eye,
  DOCUMENT_EMAILED: Mail,
  LETTER_REGISTERED: MailPlus,
  LETTER_ROUTED: Forward,
  LETTER_ASSIGNED: UserPlus,
  LETTER_EXECUTED: ClipboardCheck,
  LETTER_ACCEPTED: BadgeCheck,
  LETTER_SIGNED: PenLine,
  LETTER_DISPATCHED: SendHorizontal,
  LETTER_CLOSED: MailCheck,
  TASK_CREATED: FilePlus,
  TASK_UPDATED: Pencil,
  TASK_STARTED: CirclePlay,
  TASK_CLARIFICATION_REQUESTED: HelpCircle,
  TASK_CLARIFICATION_ANSWERED: MessageCircle,
  TASK_SUBMITTED: Send,
  TASK_ACCEPTED: CheckCircle,
  TASK_RETURNED: RefreshCw,
  TASK_REJECTED: XCircle,
};
